package isufiles;

import javax.swing.JOptionPane;

public class ERGui extends javax.swing.JFrame {

    int con;
    Patient p;
    LinkedPriorityQueue linkedQ = new LinkedPriorityQueue(3);

    public ERGui() {
        initComponents();
        txtOut.setText("NAME\tCONDITION\n----------------------------------------");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnFair = new javax.swing.JRadioButton();
        btnCritical = new javax.swing.JRadioButton();
        btnSerious = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnSchedule = new javax.swing.JButton();
        btnTreatNext = new javax.swing.JButton();
        btnTreatAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOut = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Patient Name:");

        btnFair.setBackground(new java.awt.Color(0, 240, 0));
        buttonGroup1.add(btnFair);
        btnFair.setText("Fair");
        btnFair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFair.setBorderPainted(true);

        btnCritical.setBackground(new java.awt.Color(240, 0, 0));
        buttonGroup1.add(btnCritical);
        btnCritical.setText("CRITICAL");
        btnCritical.setToolTipText("");
        btnCritical.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red));
        btnCritical.setBorderPainted(true);
        btnCritical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriticalActionPerformed(evt);
            }
        });

        btnSerious.setBackground(new java.awt.Color(240, 240, 0));
        buttonGroup1.add(btnSerious);
        btnSerious.setText("Serious");
        btnSerious.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSerious.setBorderPainted(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Condition:");

        btnSchedule.setText("Schedule");
        btnSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleActionPerformed(evt);
            }
        });

        btnTreatNext.setText("Treat Next");
        btnTreatNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreatNextActionPerformed(evt);
            }
        });

        btnTreatAll.setText("Treat All");
        btnTreatAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreatAllActionPerformed(evt);
            }
        });

        txtOut.setEditable(false);
        txtOut.setColumns(20);
        txtOut.setRows(5);
        jScrollPane1.setViewportView(txtOut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCritical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(btnFair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSerious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(167, 167, 167)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTreatNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTreatAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFair)
                    .addComponent(btnSchedule))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSerious)
                    .addComponent(btnTreatNext))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCritical)
                    .addComponent(btnTreatAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriticalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriticalActionPerformed

    private void btnScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleActionPerformed
       con = -1;
        if (btnFair.isSelected()) {//sets condition according to button selected
            con = 2;
        }
        if (btnSerious.isSelected()) {
            con = 1;
        }
        if (btnCritical.isSelected()) {
            con = 0;
        }
        if (txtName.getText().equals("") || con == -1) {
            JOptionPane.showMessageDialog(this, "Must fill form completely");//gives error if name is blank or button not selected
            return;
        }
        p = new Patient(txtName.getText(), con);//sets patient 
        linkedQ.enqueue(p, con);//queues them in proper queue
        txtOut.append(p.toString());//prints the name and condition of the patient
        buttonGroup1.clearSelection();        //sets all buttons as unselected
                
    }//GEN-LAST:event_btnScheduleActionPerformed

    private void btnTreatNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatNextActionPerformed

        txtOut.append("\nTreating:" + linkedQ.dequeue()+"... has been treated."); //removes patient from queue and prints them being treated      


    }//GEN-LAST:event_btnTreatNextActionPerformed

    private void btnTreatAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatAllActionPerformed
        txtOut.append("\nTreating all patients...\n----------------------------------------");
        while (linkedQ.peekFront()!="") {//checks if all the queues are empty            
                txtOut.append("" + linkedQ.dequeue() + "...Treating...");//treats next patient if there are any left            
        }
        txtOut.append("\nAll patients treated");
    }//GEN-LAST:event_btnTreatAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ERGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ERGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ERGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ERGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ERGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCritical;
    private javax.swing.JRadioButton btnFair;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JRadioButton btnSerious;
    private javax.swing.JButton btnTreatAll;
    private javax.swing.JButton btnTreatNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtOut;
    // End of variables declaration//GEN-END:variables
}
